name: BeaconPortals
author: Jipok
description: "Allow teleportation between Beacons"
website: https://github.com/Jipok/spigot-beacon-portals

version: 3.0
api-version: 1.15
main: Jipok.BeaconPortals.main
